#!/usr/bin/perl -w
use File::Basename;

if ((scalar @ARGV) != 4) {
	print "Usage: plan <domain> <problem> <solution> <timing>\n";
	exit(1);
}

$dir = dirname(__FILE__);
$dom = shift @ARGV;
$prob = shift @ARGV;
$soln = shift @ARGV;
$timing = shift @ARGV;

if (!(-e $dom)) {
	print "Domain file $dom not found\n";
	exit(1);
}

if (!(-e $prob)) {
  print "Problem file $prob not found\n";
  exit(1);
}

system("$dir/fast-downward.py", "--plan-file", "$soln", "$dom", "$prob", "--search", "astar(lmcut())");

# get return value of the executable
$exit_code = $? >> 8;
exit($exit_code);